save_name: DEFAULT
folders:
  data: Data
  results: Results
  load: Load
  temp: Temp
data:
  prefix: dec12_eilat
  channels: 2 
  dim: 224
training:
  max_epochs: 1000
  stop_after: 20
  print_status: 10
  batch_size: 32
  train_split: 0.8
  tune_trials: 2
  max_tune: 30
  k_folds: 5
  improve_margin: 0.001
replicable: True
seed: 42
defaults:
  dropout: 0.5
  lr: 0.0002
  decay: 0.000001
  beta1: 0.9
  beta2: 0.99
  pos: 2